# # debug.yaml
# name: 'My-2GPU-Debug-Session'
# command: 'python train.py'  # 这里写你平时运行的命令即可，但在交互模式下它不会自动执行
# is_parent: false
# resources:
#   task_type: 2gpu           # 【关键点】这里向集群申请 2 张 GPU
name: 'flextrackv2 Python Runner'
description: 'flextrackv2 Python Runner'
tags: ['flextrackv2', 'CVL']
setup_command: 'bash bolt/setup.sh'
project_id: anst_model_training
priority: 1
command: 'bash bolt/eval.sh'
scheduling_options:
  preemptible: False
cluster_options:
  aws:
    instance_type: p5.48xlarge
  gcp:
    instance_type: a2-ultragpu-8g
resources:
  cluster: aws_5
  docker_image: docker.apple.com/anst-dev/ubuntu20.04-python3.8-cuda11.8-torch2.1.1:2024-11-07
  ports: ['JUPYTER_PORT', "BOLT_TAB_Gradio"]
  timeout: 14d
  task_type: 4gpu
  disk_gb: 4000
is_parent: False
environment_variables:
  PYTHONPATH: '/mnt/task_runtime:$PYTHONPATH'
attribution:
  area: Other
  record: "Other"
permissions:
  viewers:
  - cvl-anst-training
# bolt task submit --tar FlexTrackV2/ --exclude outputs --config /Users/test/tyd/config-flextrackv2.yaml --interactive


